url: "https://cryptokarl013.xyz"
name: CryptoKarl013
title: "CryptoKarl013 - Independent Blockchain Forensics"
description: "Independent on-chain research into crypto theft, NFT-whale activity, and illicit fund flows. Evidence-based public reports built from verifiable blockchain data."

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-redirect-from

remote_theme: pages-themes/cayman@v0.2.0
author: cryptokarl013
logo: https://avatars.githubusercontent.com/u/212721571?s=400&u=15fab0c2b8fe82ab05e1ab1d50b8e927a8143393&v=4
show_downloads: false
google_analytics: G-C90F5LHLFF
social:
  name: GitHub
  links:
    - https://github.com/cryptokarl013
    - https://x.com/CryptoKarl013

twitter:
  username: CryptoKarl013
  card: summary_large_image

include:
  - "robots.txt"

exclude:
  - "yandex_5d68f6d05da5caf2.html"
  - "report-0134-stolen-ETHs-Leads-to-NFT-Whales-n0b0dy-indifferent-and-investments-into-a-real-company-undeadscom"
  - "report-0135-657-solana-wallets-drained-by-deQzbGSDA3U6bFmxAfWuJYhYBvN647fP1i8DEDoVNW3-on-09102025"

defaults:
  - scope:
      path: ""
    values:
      author: cryptokarl013
